### PR TITLE
Show admin notice to those on less than PHP 5.3

### LINKED ISSUE #25: Fatal error on PHP 5.2
When activated on a site with PHP 5.2, a fatal error is thrown:
```
Fatal error: syntax error, unexpected T_FUNCTION in /Users/pippin/Sites/edd/wp-content/plugins/affiliatewp-affiliate-area-tabs/affiliatewp-affiliate-area-tabs.php on line 225
```
We don't need to support 5.2 but do we need to prevent an error from being thrown.

### PR DESCRIPTION
**Pull request by sumobi**
Fix #25

### CODE REVIEW

**Comment by sumobi** [comment]
@pippinsplugins happy with this?

File: affiliatewp-affiliate-area-tabs.php [hunk 1]
```diff
@@ -527,16 +527,29 @@ public function plugin_meta( $links, $file ) {
...
+			if ( ! class_exists( 'AffiliateWP_Activation' ) ) {
+	            require_once 'includes/class-activation.php';
+	        }
+
+			$activation = new AffiliateWP_Activation( plugin_dir_path( __FILE__ ), basename( __FILE__ ) );
+	        $activation = $activation->below_php_version();
+
+		} else {
 	        return AffiliateWP_Affiliate_Area_Tabs::instance();
 	    }
```
Comment (pippinsplugins) [inline affiliatewp-affiliate-area-tabs.php]: Looks like we have some indention issues here.
